services:
  - type: web
    name: siridev-backend
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn siridev_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.5
      - key: DATABASE_URL
        fromDatabase:
          name: siridev-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://siridev-frontend-44ga.onrender.com,http://localhost:3000

databases:
  - name: siridev-db
    databaseName: siridev
    user: siridev
    plan: free
